### ISSUE TITLE
Plugins are outdated.

### ISSUE THREAD

**Issue by DogancanYr** [mov-ebx/BannedBetterDiscordPlugins#1]
Update the plugins yourself or put the download link of the original producer.

**Comment by mov-ebx** [comment]
All the links are from the original authors or written at the bottom of the page in a section called "Other links"

**Comment by DogancanYr** [comment]
> All the links are from the original authors or written at the bottom of the page in a section called "Other links"
If you're not going to update the plugins, what's the point of them being there?
